
import { Product } from './types';

export const PRODUCTS: Product[] = [
  // --- SHIRTS ---
  {
    id: 's1',
    name: 'Cotton Oxford Blue',
    price: 25500,
    category: 'Shirts',
    description: 'A timeless classic in breathable cotton. Perfect for both office and weekend wear.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/IRE_2918_1270x.jpg?v=1755103469',
    colors: ['Light Blue', 'White'],
    sizes: ['S', 'M', 'L', 'XL'],
    fit: 'Slim Fit',
    inStock: true
  },
  {
    id: 's2',
    name: 'Linen Vacation Stripe',
    price: 18000,
    originalPrice: 22500,
    onSale: true,
    category: 'Shirts',
    description: 'Relaxed fit shirt crafted from high-quality European linen.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/0y2a8022_1170x.jpg?v=1753177606',
    colors: ['Stripe Blue', 'Beige'],
    sizes: ['M', 'L', 'XL'],
    fit: 'Relaxed Fit',
    inStock: true
  },
  {
    id: 's3',
    name: 'Grandad Collar White',
    price: 27000,
    category: 'Shirts',
    description: 'Minimalist band-collar shirt in a crisp cotton poplin.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/IRE_2910_1270x.jpg?v=1755103246',
    colors: ['Off-White', 'Stone'],
    sizes: ['S', 'M', 'L'],
    fit: 'Slim Fit',
    inStock: true
  },
  // --- SHOES ---
  {
    id: 'sh1',
    name: 'Heritage Oxford Walnut',
    price: 38500,
    category: 'Shoes',
    description: 'Classic wingtip oxford in premium calfskin leather with a hand-burnished finish.',
    image: 'https://shoes.lk/cdn/shop/files/227.png?v=1766916199&width=360',
    colors: ['Walnut'],
    sizes: ['7', '8', '9', '10', '11'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'sh2',
    name: 'Artisan Derby Brown',
    price: 36000,
    category: 'Shoes',
    description: 'Versatile derby shoe featuring a durable rubber sole for all-day comfort.',
    image: 'https://shoes.lk/cdn/shop/files/67_ebd97e29-a224-4a09-aa63-2f300cca66df.png?v=1765305337&width=360',
    colors: ['Dark Brown'],
    sizes: ['7', '8', '9', '10', '11'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'sh3',
    name: 'Modern Monk Strap',
    price: 41000,
    category: 'Shoes',
    description: 'Sleek double monk strap design for a sharp, contemporary professional look.',
    image: 'https://shoes.lk/cdn/shop/files/65.png?v=1765304642&width=360',
    colors: ['Black'],
    sizes: ['8', '9', '10'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'sh4',
    name: 'Elysian Loafer Tan',
    price: 34500,
    category: 'Shoes',
    description: 'Refined penny loafer in soft suede, perfect for smart-casual summer styling.',
    image: 'https://shoes.lk/cdn/shop/files/68_8748425f-b5a8-46d6-91e7-937c34ffdf13.png?v=1765304504&width=360',
    colors: ['Tan'],
    sizes: ['7', '8', '9', '10'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'sh5',
    name: 'Urban Leather Sneaker',
    price: 29500,
    category: 'Shoes',
    description: 'Minimalist white leather sneakers that define modern versatility.',
    image: 'https://shoes.lk/cdn/shop/files/NKM003_3ce82ce7-500f-4d90-8d51-620331aa692c.png?v=1751365889&width=360',
    colors: ['White'],
    sizes: ['7', '8', '9', '10', '11'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'sh6',
    name: 'Midnight Chelsea Boot',
    price: 45000,
    category: 'Shoes',
    description: 'Architectural Chelsea boots in matte black leather with elastic gussets.',
    image: 'https://shoes.lk/cdn/shop/files/NKS001_18be14ea-7189-4429-8fa1-8025163a4253.png?v=1751539757&width=360',
    colors: ['Black'],
    sizes: ['8', '9', '10', '11'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'sh7',
    name: 'Rustic Suede Boot',
    price: 43000,
    category: 'Shoes',
    description: 'Hand-finished suede boots with a rugged yet refined profile.',
    image: 'https://shoes.lk/cdn/shop/files/NKS002_244dc9f1-4154-453a-8544-893761695a08.png?v=1751539485&width=360',
    colors: ['Tobacco'],
    sizes: ['7', '8', '9', '10'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'sh8',
    name: 'Contemporary Brogue',
    price: 39500,
    category: 'Shoes',
    description: 'Intricate wingtip detailing paired with a modern wedge sole.',
    image: 'https://shoes.lk/cdn/shop/files/NKS003_16dd92ef-21b1-48b4-885e-e3ba7726249f.png?v=1751539617&width=360',
    colors: ['Oxblood'],
    sizes: ['8', '9', '10', '11'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'sh9',
    name: 'Sovereign Evening Shoe',
    price: 48000,
    category: 'Shoes',
    description: 'The pinnacle of formal footwear, high-shine patent leather for your most special occasions.',
    image: 'https://shoes.lk/cdn/shop/files/79.png?v=1766918685&width=360',
    colors: ['Black Patent'],
    sizes: ['8', '9', '10'],
    fit: 'Standard',
    inStock: true
  },
  // --- BAGS ---
  {
    id: 'b1',
    name: 'Heritage Leather Duffle',
    price: 42500,
    category: 'Bags',
    description: 'The ultimate travel companion, crafted from rich, full-grain leather that patinas beautifully over time.',
    image: 'https://bag.lk/wp-content/uploads/2025/12/10-4.webp',
    colors: ['Cognac'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'b2',
    name: 'Executive Briefcase',
    price: 38000,
    category: 'Bags',
    description: 'Command the boardroom with this structured leather briefcase, featuring dedicated compartments for tech and documents.',
    image: 'https://bag.lk/wp-content/uploads/2025/12/7612.webp',
    colors: ['Black'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'b3',
    name: 'Signature Slim Portfolio',
    price: 22500,
    category: 'Bags',
    description: 'A minimalist approach to professional carry, designed for the modern minimalist.',
    image: 'https://bag.lk/wp-content/uploads/2025/12/7612_4.webp',
    colors: ['Ebony'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'b4',
    name: 'Nomad Travel Holdall',
    price: 45000,
    category: 'Bags',
    description: 'Spacious and durable, this holdall is built for short escapes and weekend getaways.',
    image: 'https://bag.lk/wp-content/uploads/2025/12/7612-1.webp',
    colors: ['Mahogany'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'b5',
    name: 'Urban Commuter Backpack',
    price: 31500,
    category: 'Bags',
    description: 'Blending functionality with a sleek urban aesthetic, perfect for daily transit.',
    image: 'https://bag.lk/wp-content/uploads/2025/12/1-7.webp',
    colors: ['Dark Brown'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'b6',
    name: 'Vintage Messenger Bag',
    price: 28500,
    category: 'Bags',
    description: 'Inspired by classic silhouettes, this messenger bag offers easy access and a rugged charm.',
    image: 'https://bag.lk/wp-content/uploads/2025/12/6886-1.webp',
    colors: ['Tan'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'b7',
    name: 'Craftsman Crossbody',
    price: 19500,
    category: 'Bags',
    description: 'Compact and secure, ideal for your essential daily carry items.',
    image: 'https://bag.lk/wp-content/uploads/2025/12/15-2048x2048.webp',
    colors: ['Chocolate'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'b8',
    name: 'Artisan Leather Tote',
    price: 24000,
    category: 'Bags',
    description: 'Hand-stitched leather tote with an open top for easy access and a refined look.',
    image: 'https://bag.lk/wp-content/uploads/2025/12/ChatGPT-Image-Dec-13-2025-05_34_38-PM.webp',
    colors: ['Sienna'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'b9',
    name: 'Premium Laptop Sleeve',
    price: 15500,
    category: 'Bags',
    description: 'Sleek protection for your hardware, lined with soft microfiber.',
    image: 'https://bag.lk/wp-content/uploads/2025/12/10-2048x2048.webp',
    colors: ['Onyx'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  // --- POLOS ---
  {
    id: 'p1',
    name: 'Signature Pique Polo Navy',
    price: 12500,
    category: 'Polos',
    description: 'A classic pique knit with refined detailing and a perfect slim fit.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/SC__1183_1880x.jpg?v=1739189816',
    colors: ['Navy'],
    sizes: ['S', 'M', 'L', 'XL'],
    fit: 'Slim Fit',
    inStock: true
  },
  {
    id: 'p2',
    name: 'Essential Polo Charcoal',
    price: 12500,
    category: 'Polos',
    description: 'Versatile charcoal polo made from premium long-staple cotton.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/SC__1167_1880x.jpg?v=1739190074',
    colors: ['Charcoal'],
    sizes: ['S', 'M', 'L', 'XL'],
    fit: 'Regular Fit',
    inStock: true
  },
  {
    id: 'p3',
    name: 'Luxe Knit Polo Emerald',
    price: 14500,
    category: 'Polos',
    description: 'Sophisticated knit texture for a more formal take on the casual classic.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/IMG_2119-Edit_1270x.jpg?v=1723618426',
    colors: ['Emerald'],
    sizes: ['M', 'L', 'XL'],
    fit: 'Slim Fit',
    inStock: true
  },
  {
    id: 'p4',
    name: 'Sky Blue Pique Polo',
    price: 12000,
    category: 'Polos',
    description: 'Breathable and light, ideal for the tropical climate of Colombo.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/IMG_2181-Edit_1270x.jpg?v=1723617603',
    colors: ['Sky Blue'],
    sizes: ['S', 'M', 'L'],
    fit: 'Regular Fit',
    inStock: true
  },
  {
    id: 'p5',
    name: 'Classic White Polo',
    price: 12000,
    category: 'Polos',
    description: 'Crisp white polo with a subtly contrasting collar tipping.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/IMG_2241-Edit_1270x.jpg?v=1723615667',
    colors: ['White'],
    sizes: ['S', 'M', 'L', 'XL'],
    fit: 'Slim Fit',
    inStock: true
  },
  {
    id: 'p6',
    name: 'Textured Melange Polo',
    price: 13500,
    category: 'Polos',
    description: 'A melange weave that adds depth and character to your ensemble.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/Untitleddesign_5_b1047592-abc1-423b-83fb-348407e9bdf9_1570x.png?v=1712139687',
    colors: ['Grey Melange'],
    sizes: ['M', 'L', 'XL'],
    fit: 'Regular Fit',
    inStock: true
  },
  {
    id: 'p7',
    name: 'Heritage Striped Polo',
    price: 14000,
    category: 'Polos',
    description: 'Iconic stripe design featuring a soft-wash finish for ultimate comfort.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/IRE_2940_1270x.jpg?v=1755103627',
    colors: ['Navy/White'],
    sizes: ['S', 'M', 'L'],
    fit: 'Slim Fit',
    inStock: true
  },
  {
    id: 'p8',
    name: 'Regatta Polo Red',
    price: 13000,
    category: 'Polos',
    description: 'Bold red with a structured collar that stays sharp all day.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/IRE_2946_1270x.jpg?v=1755103697',
    colors: ['Red'],
    sizes: ['M', 'L', 'XL'],
    fit: 'Regular Fit',
    inStock: true
  },
  // --- DENIMS ---
  {
    id: 'd1',
    name: 'Selvedge Indigo Classic',
    price: 32500,
    category: 'Denims',
    description: 'Raw indigo denim crafted on vintage looms for the purist.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/SC__1257_1880x.jpg?v=1739794641',
    colors: ['Raw Indigo'],
    sizes: ['30', '32', '34', '36'],
    fit: 'Regular Fit',
    inStock: true
  },
  {
    id: 'd2',
    name: 'Stay Black Tailored',
    price: 29500,
    category: 'Denims',
    description: 'Deep black denim with a tailored silhouette.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/SC__1420_1880x.jpg?v=1738068126',
    colors: ['Solid Black'],
    sizes: ['30', '32', '34', '36'],
    fit: 'Slim Fit',
    inStock: true
  },
  {
    id: 'd4',
    name: 'Heritage Straight Fit',
    price: 31000,
    category: 'Denims',
    description: 'A classic straight leg in a mid-wash indigo, built for durability and comfort.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/SC__1246_1880x.jpg?v=1739794641',
    colors: ['Indigo'],
    sizes: ['30', '32', '34', '36'],
    fit: 'Regular Fit',
    inStock: true
  },
  {
    id: 'd5',
    name: 'Tapered Charcoal Denim',
    price: 30500,
    category: 'Denims',
    description: 'Washed charcoal finish with a modern tapered leg. Versatile and sharp.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/SC__1194_1880x.jpg?v=1739794558',
    colors: ['Charcoal'],
    sizes: ['30', '32', '34', '36'],
    fit: 'Slim Fit',
    inStock: true
  },
  // --- ACCESSORIES ---
  {
    id: 'acc1',
    name: 'Artisan Woven Tie',
    price: 8500,
    category: 'Accessories',
    description: 'Exquisite silk tie with a subtle textured weave.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/WhatsAppImage2025-09-09at12.20.53_1880x.jpg?v=1757404256',
    colors: ['Deep Blue'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc2',
    name: 'Signature Silk Square',
    price: 5500,
    category: 'Accessories',
    description: 'Hand-rolled edges and a refined geometric print.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/WhatsAppImage2025-09-09at12.20.54_1880x.jpg?v=1757404027',
    colors: ['Burgundy'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc3',
    name: 'Modern Knit Tie',
    price: 7500,
    category: 'Accessories',
    description: 'A contemporary take on the necktie, perfect for smart-casual styling.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/WhatsAppImage2025-09-09at12.20.54_1_1880x.jpg?v=1757403274',
    colors: ['Emerald'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc4',
    name: 'Classic Leather Belt',
    price: 12500,
    category: 'Accessories',
    description: 'Full-grain Italian leather with a brushed silver buckle.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/WhatsAppImage2025-09-09at12.20.55_1880x.jpg?v=1757403479',
    colors: ['Tan'],
    sizes: ['32', '34', '36'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc5',
    name: 'Heritage Cufflinks',
    price: 9500,
    category: 'Accessories',
    description: 'Polished steel with a minimalist monogram engraving.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/WhatsAppImage2025-09-09at12.20.56_1880x.jpg?v=1757403615',
    colors: ['Silver'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc6',
    name: 'Premium Wool Scarf',
    price: 15500,
    category: 'Accessories',
    description: 'Ultra-soft merino wool for timeless warmth.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/WhatsAppImage2025-09-09at12.20.56_1_1880x.jpg?v=1757403888',
    colors: ['Grey'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc7',
    name: 'Essentials Bow Tie',
    price: 6500,
    category: 'Accessories',
    description: 'Pre-tied for convenience without sacrificing elegance.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/EssentialsCollection-web_22_1880x.png?v=1722838523',
    colors: ['Black'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc8',
    name: 'Artisan Leather Wallet',
    price: 18500,
    category: 'Accessories',
    description: 'Slim bifold design crafted from sustainably sourced leather.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/WhatsAppImage2025-09-04at12.29.47_1880x.jpg?v=1757398314',
    colors: ['Chocolate'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc9',
    name: 'Formal Suede Belt',
    price: 11500,
    category: 'Accessories',
    description: 'Soft suede texture for a refined evening look.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/WhatsAppImage2025-09-04at12.29.55_1880x.jpg?v=1757399790',
    colors: ['Navy'],
    sizes: ['32', '34', '36'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc10',
    name: 'Geometric Silk Tie',
    price: 8500,
    category: 'Accessories',
    description: 'Sophisticated micro-pattern for the modern professional.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/WhatsAppImage2025-09-04at12.30.03_1_1880x.jpg?v=1757400021',
    colors: ['Wine'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc11',
    name: 'Minimalist Card Holder',
    price: 9000,
    category: 'Accessories',
    description: 'Ultra-thin profile for your essential cards.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/EssentialsCollection-web_16_1880x.png?v=1722836040',
    colors: ['Black'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc12',
    name: 'Patterned Wool Tie',
    price: 10500,
    category: 'Accessories',
    description: 'Textured wool blend with a classic houndstooth weave.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/WhatsAppImage2025-09-04at12.30.03_1880x.jpg?v=1757400360',
    colors: ['Charcoal'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc13',
    name: 'Evening Cufflink Set',
    price: 12000,
    category: 'Accessories',
    description: 'Silver-tone base with an onyx inlay.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/WhatsAppImage2025-09-09at12.20.53_1_1880x.jpg?v=1757404153',
    colors: ['Onyx'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc14',
    name: 'Monogram Linen Square',
    price: 4500,
    category: 'Accessories',
    description: 'Crisp Irish linen with a refined border.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/EssentialsCollection-web_14_1880x.png?v=1722835380',
    colors: ['White'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc15',
    name: 'Braided Leather Belt',
    price: 13500,
    category: 'Accessories',
    description: 'Intricate hand-braided detail for casual elegance.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/20231213_133100_1_1880x.jpg?v=1702979636',
    colors: ['Brown'],
    sizes: ['32', '34', '36'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc16',
    name: 'Luxury Tie Bar',
    price: 6000,
    category: 'Accessories',
    description: 'Sleek matte finish to keep your ensemble perfectly placed.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/Essentials_Collection_-_web_3_1880x.png?v=1722423798',
    colors: ['Gunmetal'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  {
    id: 'acc17',
    name: 'Dotted Silk Tie',
    price: 8500,
    category: 'Accessories',
    description: 'Timeless polka dots on high-lustre silk.',
    image: 'https://stripesandchecksinc.com/cdn/shop/files/Essentials_Collection_-_web_24_1880x.png?v=1722839233',
    colors: ['Navy Dot'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  },
  // --- CHINOS ---
  {
    id: 'c1',
    name: 'Slim Fit Twill Chinos',
    price: 28500,
    category: 'Chinos',
    description: 'Stretch cotton twill chinos that transition perfectly from desk to dinner.',
    image: 'https://images.unsplash.com/photo-1624371414361-e6e0ed2bf527?auto=format&fit=crop&q=80&w=800',
    colors: ['Khaki', 'Olive', 'Black'],
    sizes: ['30', '32', '34', '36'],
    fit: 'Slim Fit',
    inStock: true
  },
  {
    id: 'c2',
    name: 'Relaxed Tapered Chinos',
    price: 21000,
    originalPrice: 34500,
    onSale: true,
    category: 'Chinos',
    description: 'A more casual silhouette for effortless daily wear.',
    image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&q=80&w=800',
    colors: ['Grey', 'Dusty Blue'],
    sizes: ['32', '34', '36'],
    fit: 'Relaxed Fit',
    inStock: true
  },
  // --- SALE EXCLUSIVES ---
  {
    id: 'sale_m1',
    name: 'Moose Comfort Fit Crew Neck - Patriot Blue',
    price: 3200,
    originalPrice: 4500,
    onSale: true,
    category: 'Polos',
    description: 'A premium comfort-fit crew neck t-shirt in a deep patriot blue shade.',
    image: 'https://thilakawardhana.com/cdn/shop/files/TM15166.1_1880x.jpg?v=1765691538',
    colors: ['Patriot Blue'],
    sizes: ['S', 'M', 'L', 'XL'],
    fit: 'Regular Fit',
    inStock: true
  },
  {
    id: 'sale_m2',
    name: 'Moose Everyday Essential Tee - White',
    price: 2800,
    originalPrice: 3800,
    onSale: true,
    category: 'Polos',
    description: 'The ultimate base layer. Soft, breathable cotton in a crisp white finish.',
    image: 'https://thilakawardhana.com/cdn/shop/files/TM15163.1_1880x.jpg?v=1765628579',
    colors: ['White'],
    sizes: ['S', 'M', 'L', 'XL'],
    fit: 'Regular Fit',
    inStock: true
  },
  {
    id: 'sale_m3',
    name: 'Mens Slim Fit Mid Washed Jean',
    price: 8500,
    originalPrice: 12500,
    onSale: true,
    category: 'Denims',
    description: 'Tailored slim fit with a classic mid-wash finish for a timeless look.',
    image: 'https://thilakawardhana.com/cdn/shop/files/TM15161.2_1880x.jpg?v=1765628170',
    colors: ['Mid Wash'],
    sizes: ['30', '32', '34', '36'],
    fit: 'Slim Fit',
    inStock: true
  },
  {
    id: 'v500',
    name: 'Digital Gift Voucher 150000 LKR',
    price: 150000,
    category: 'Vouchers',
    description: 'The ultimate luxury gift for the discerning modern man.',
    image: 'https://images.unsplash.com/photo-1512909006721-3d6018887383?auto=format&fit=crop&q=80&w=800',
    colors: ['Elysian Gold'],
    sizes: ['OS'],
    fit: 'Standard',
    inStock: true
  }
];
